### ISSUE TITLE
Enable clippy

### ISSUE THREAD

**Issue by sayanarijit** [tui-rs-revival/tui-rs-revival#53]
Clippy will be disabled in https://github.com/tui-rs-revival/tui-rs-revival/pull/51.

This issue is to re-enable clippy with linting fixes.

**Comment by rhysd** [comment]
What is an issue which prevents re-enabling clippy on CI?

**Comment by rhysd** [comment]
I ran `cargo clippy` on my local and it didn't report any warnings. It might happen due to older version of clippy.

**Comment by rhysd** [comment]
OK, I'll try to re-enable clippy.
