### ISSUE TITLE
Question about the fork

### ISSUE THREAD

**Issue by ckampfe** [tui-rs-revival/tui-rs-revival#55]
Hello all, I've been following https://github.com/fdehau/tui-rs/issues/654 with interest!

I maintain an RSS/Atom reader called [Russ](https://github.com/ckampfe/russ) that is built on `tui-rs` (please feel free to add it to the list of projects using `tui-rs`, as I am extremely pleased with and grateful for `tui-rs`). 

My question is this: given the fork, with regard to bug reports/feature requests/PRs, should I file those here, or upstream? Is the plan to merge the work in this fork upstream, or have this fork eventually replace upstream? Thank you to everyone actively working to keep `tui-rs` going, it's such a lovely project.

**Comment by mindoodoo** [comment]
Hey,

For the time being, we are treating this fork as the new "official fork" meaning that if you have any issue or PR, you should open them **here.**
If the original maintainer responds, we will most likely merge this repo into it, but this should be considered the maintained repository for the time being as that does not seem likely at this point.

Also do feel free to join our discord if you want to contribute or follow the project more closely.

**Comment by ckampfe** [comment]
@mindoodoo thank you very much for the response.
